Repackage workspace, workflow, taskqueue and activity libraries. Add infrastructure tests.
Biomapas/B.CfnTwilio pull request #1
Opened 2022-01-03 08:47 UTC by robertasstankevicius

2022-01-03 14:51 UTC, laimonassutkus requested changes
Hide singleton functions.

2022-01-03 14:51 UTC, laimonassutkus commented on README.md
> +    workspace_function=TwilioWorkspaceSingletonFunction(
Hide this function withing custom resource.

2022-01-03 14:51 UTC, laimonassutkus commented on README.md
> +    task_queue_function=TwilioTaskQueueSingletonFunction(
Hide this function withing custom resource.

2022-01-03 14:51 UTC, laimonassutkus commented on README.md
> +    workflow_function=TwilioWorkflowSingletonFunction(
Hide this function withing custom resource.

2022-01-04 08:20 UTC, laimonassutkus requested changes
Mainly esthetical issues.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/resource.py
> +    Creates a workspace on stack creation.
Get your docstrings fixed. Docstrings are for giving information, not confusing developers when you just copy-paste.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/resource.py
> +    def __parametrize_name(self, friendly_name: str) -> str:
Docstring. Explain why are you doing this parametrization.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/resource.py
> +    def get_activity_sid(self, friendly_name: str) -> str:
Docstring.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/source/main/action.py
> +            if key.endswith('Activity')
Explain with comment what kind of validation/magic are you performing here.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/source/main/action.py
> +        # Set the default cfn_activity.
What is this cfn_activity. Did you just run "ctrl+shift+R" and changed everything from "activity" to "cfn_activity"?

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/source/main/action.py
> +        # Delete unused default activities.
Why does the "Create" function deletes something?

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/source/main/action.py
> +        # It is safe to assume that this value will always be set in the following loop, since the resource requires exactly one cfn_activity to be default.
cfn_activity

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/source/main/action.py
> +        # It is safe to assume that this value will always be set in the following loop, since the resource requires exactly one cfn_activity to be default.
not mentioning further

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/source/main/cfnresponse.py
> +import logging
Since you are using "TwilioLayer" and every custom resource has one, use https://github.com/Biomapas/B.AwsCfResponse instead of heavy code duplication.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_activity/twilio_activity.py
> +class TwilioActivity:
Add docstring at least to the class.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_task_queue/resource.py
> +    Creates a task_queue on stack creation.
task_queue or task queue? :) This is a docstring, not a code.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_task_queue/resource.py
> +    def task_queue_sid(self):
-> str

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_task_queue/source/main/cfnresponse.py
> +import logging
Same here.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_workflow/source/main/cfnresponse.py
> +import logging
Same here.

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_workspace/resource.py
> +    def workspace_sid(self):
-> str

2022-01-04 08:20 UTC, laimonassutkus commented on b_cfn_twilio/cfn_workspace/source/main/cfnresponse.py
> +import logging
same here

2022-01-04 08:20 UTC, laimonassutkus commented on setup.py
> +    author='Laimonas Sutkus',
Robertas

2022-01-04 08:20 UTC, laimonassutkus commented on setup.py
> +    author_email='laimonas.sutkus@biomapas.com',
robertas.email@email.com

2022-01-04 09:22 UTC, robertasstankevicius commented on b_cfn_twilio/cfn_activity/source/main/action.py
> +        # Delete unused default activities.
Because there are activities created by default, that could not be defined by user - therefore not needed.

2022-01-04 12:09 UTC, robertasstankevicius commented on b_cfn_twilio/cfn_activity/source/main/action.py
> +            if key.endswith('Activity')
This was unnecessary and is now removed.

2022-01-04 14:03 UTC, laimonassutkus approved these changes
Job well done!

2022-01-04 14:03 UTC, merged